[package]
name = "px-her0-led"
version = "0.1.0"
authors = ["paulmeier"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
